before_install:
  - npm i -g npm@6.4.1
language: node_js
node_js:
  - "node"
  - "11"
script: npm run build
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  on:
    branch: master
